behaviors:
  Drive:
    trainer_type: ppo
    hyperparameters:
      batch_size: 2024
      buffer_size: 20240
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 512
      num_layers: 3
    reward_signals:
      gail:
        gamma: 0.99
        strength: 0.0
        network_settings:
          normalize: true
          hidden_units: 128
          num_layers: 2
          vis_encode_type: simple
        demo_path: Demos/Drive.demo
    behavioral_cloning:
      strength: 1.0
      demo_path: Demos/Drive.demo
      steps: 50000
    max_steps: 5000000
    time_horizon: 64
    summary_freq: 10000